# Generated by Django 3.2.9 on 2021-11-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=250)),
                ('code', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.TextField(max_length=100)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('browwer_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.customer_info')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('a_c_number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('Balance', models.IntegerField()),
                ('Customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.customer_info')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.bank')),
            ],
        ),
    ]
